/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kenjiebalona
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(12, 19, 79));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 72)); // NOI18N
        jLabel1.setText("Immortal Ako!!!!! <3");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("i♥ ♥m♥i♥s♥s♥ ♥h♥e♥r♥ ♥s♥o♥ ♥m♥u♥c♥h");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setText("🍎  🎀  𝒾 𝓂𝒾𝓈𝓈 𝒽𝑒𝓇 𝓈🍬 𝓂𝓊𝒸𝒽  🎀  🍎");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setText("˜”*°•.˜”*°• I find myself lost in the quiet moments, •°*”˜.•°*”˜");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setText("🆆🅷🅴🆁🅴 🆃🅷🅴 🆆🅾🆁🅻🅳 🆂🅻🅾🆆🆂 🅳🅾🆆🅽 🅹🆄🆂🆃 🅴🅽🅾🆄🅶🅷 🅵🅾🆁 🅼🅴 🆃🅾 🆁🅴🅰🅻🅸🆉🅴 🆈🅾🆄'🆁🅴 🅽🅾🆃 🆃🅷🅴🆁🅴.");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel6.setText("ᵀʰᵉ ʷᵒʳˡᵈ ⁱˢⁿ'ᵗ ᵃˢ ᵇʳⁱᵍʰᵗ ʷⁱᵗʰᵒᵘᵗ ʸᵒᵘʳ ˡᵃᵘᵍʰᵗᵉʳ, ᵃⁿᵈ ᵗʰᵉ ⁿⁱᵍʰᵗˢ ᵃʳᵉ ᶜᵒˡᵈᵉʳ ʷⁱᵗʰᵒᵘᵗ ʸᵒᵘʳ ʷᵃʳᵐᵗʰ. ");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel7.setText("(っ◔◡◔)っ ♥ I miss the way your eyes sparkled when you spoke about your dreams, the way your hand fit perfectly in mine. ♥");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setText("🌠⋆  🎀  𝐼 𝓂𝒾𝓈𝓈 💙𝓊𝓇 𝓈𝒽𝒶𝓇𝑒𝒹 𝓈𝓂𝒾𝓁𝑒𝓈, ❀𝓊𝓇 𝓈𝒽𝒶𝓇𝑒𝒹 𝓈𝑒𝒸𝓇𝑒𝓉𝓈, 𝒶𝓃𝒹 🍬𝓊𝓇 𝓈𝒽𝒶𝓇𝑒𝒹 𝓈𝒾𝓁𝑒𝓃𝒸𝑒𝓈.  🎀  ⋆🌠");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel9.setText("L͎i͎f͎e͎ ͎w͎i͎t͎h͎o͎u͎t͎ ͎y͎o͎u͎ ͎f͎e͎e͎l͎s͎ ͎l͎i͎k͎e͎ ͎a͎ ͎m͎o͎v͎i͎e͎ ͎t͎h͎a͎t͎'͎s͎ ͎l͎o͎s͎t͎ ͎i͎t͎s͎ ͎c͎o͎l͎o͎r͎.͎");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel10.setText("I YEᗩᖇᑎ ᖴOᖇ TᕼE ᗪᗩY ᗯᕼEᑎ ᗪIᔕTᗩᑎᑕE ᑎO ᒪOᑎGEᖇ KEEᑭᔕ ᑌᔕ ᗩᑭᗩᖇT.");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel11.setText("🅄🄽🅃🄸🄻 🅃🄷🄴🄽, 🄸 🄷🄾🄻🄳 🄾🄽 🅃🄾 🅃🄷🄴 🄼🄴🄼🄾🅁🄸🄴🅂, 🅃🄷🄴 🄴🄲🄷🄾🄴🅂 🄾🄵 🅈🄾🅄🅁 🄻🄰🅄🄶🄷🅃🄴🅁, 🅃🄷🄴 🄸🄼🄿🅁🄸🄽🅃 🄾🄵 🅈🄾🅄🅁 🅃🄾🅄🄲🄷.");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel12.setText("🐳 ⋆ 🐥  🎀  𝒴❁𝓊 𝒶𝓇𝑒 𝒹𝑒𝑒𝓅𝓁𝓎 𝓂𝒾𝓈𝓈𝑒𝒹, 𝓂💮𝓇𝑒 𝓉𝒽𝒶𝓃 𝓌💍𝓇𝒹𝓈 𝒸𝒶𝓃 𝒶𝒹𝑒𝓆𝓊𝒶𝓉𝑒𝓁𝓎 𝑒𝓍𝓅𝓇𝑒𝓈𝓈.  🎀  🐥 ⋆ 🐳");

        jLabel13.setText("(¯´•._.•   🎀  - 𝒦𝑒𝓃𝒿𝒾𝑒 𝐵𝒶𝓁♡𝓃𝒶 🥰🥲😭🥺  🎀   •._.•´¯(");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(jLabel2))))
                        .addGap(395, 395, 395)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
