/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anon
 */
public class JLoanApplication extends javax.swing.JFrame {
    Connect conn;
    private JLoanApplication loanApplicationForm = null;
    private int userID;
    String type;
     Double loanamount;
     Double annualinterest;
     int loanterm;
     Double annual;
     Double downpay;
     
     //loan deatils
       
    
    public JLoanApplication(int userID) {
    this.userID = userID;  // set this.userID to the passed userID
    initComponents();
    conn = new Connect();
    SetDetails(this.userID); // call SetDetails using this.userID
}
   
    /**
     * Creates new form JLoanApplication
     */
 
    public void SetDetails(int userID){
        User user = conn.getUserDetails(userID);
        if (user != null) {
        txtName.setText(user.getFullName());
        txtAddress.setText(user.getAddress());
        txtEmail.setText(user.getEmail());
        txtPhone.setText(user.getPhoneNumber());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JEmployment = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        empFName = new javax.swing.JTextField();
        empLName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        appOcupation = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        empAddress = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        JEmployHeader = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        empNo = new javax.swing.JTextField();
        JContanInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        rbtnSingle = new javax.swing.JRadioButton();
        rbtnMarried = new javax.swing.JRadioButton();
        rbtnWidowed = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        JLoanInfo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        loanAmount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        annualIncome = new javax.swing.JTextField();
        loanType = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        loanTerm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLoanHeader = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        loanLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        interestRate = new javax.swing.JTextField();
        downPayment = new javax.swing.JButton();
        jTitleBar = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1026, 630));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Employer's First Name");

        empFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empFNameActionPerformed(evt);
            }
        });

        empLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empLNameActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Employer's Last Name");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Applicant's Occupation");

        empAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empAddressActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Work Address");

        JEmployHeader.setBackground(new java.awt.Color(0, 0, 102));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Employment Information");

        javax.swing.GroupLayout JEmployHeaderLayout = new javax.swing.GroupLayout(JEmployHeader);
        JEmployHeader.setLayout(JEmployHeaderLayout);
        JEmployHeaderLayout.setHorizontalGroup(
            JEmployHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JEmployHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JEmployHeaderLayout.setVerticalGroup(
            JEmployHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JEmployHeaderLayout.createSequentialGroup()
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Employer's Number");

        javax.swing.GroupLayout JEmploymentLayout = new javax.swing.GroupLayout(JEmployment);
        JEmployment.setLayout(JEmploymentLayout);
        JEmploymentLayout.setHorizontalGroup(
            JEmploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JEmployHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JEmploymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JEmploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JEmploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empAddress)
                    .addGroup(JEmploymentLayout.createSequentialGroup()
                        .addComponent(appOcupation, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel18)
                        .addGap(12, 12, 12)
                        .addComponent(empNo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JEmploymentLayout.createSequentialGroup()
                        .addComponent(empFName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empLName)))
                .addContainerGap())
        );
        JEmploymentLayout.setVerticalGroup(
            JEmploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JEmploymentLayout.createSequentialGroup()
                .addComponent(JEmployHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JEmploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empFName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empLName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JEmploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JEmploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(8, 8, 8)
                .addGroup(JEmploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JEmploymentLayout.createSequentialGroup()
                        .addGroup(JEmploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel18))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(empNo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(appOcupation))
                .addGap(17, 17, 17))
        );

        jPanel1.add(JEmployment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 710, 160));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Address:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Sex:");

        rbtnMale.setText("M");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });

        rbtnFemale.setText("F");
        rbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemaleActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Marital Status:");

        rbtnSingle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnSingle.setText("Single");
        rbtnSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSingleActionPerformed(evt);
            }
        });

        rbtnMarried.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnMarried.setText("Married");
        rbtnMarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMarriedActionPerformed(evt);
            }
        });

        rbtnWidowed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnWidowed.setText("Widowed");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("E-mail:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Phone:");

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact Information");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(529, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9)
        );

        txtName.setEditable(false);

        txtAddress.setEditable(false);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtEmail.setEditable(false);

        txtPhone.setEditable(false);

        javax.swing.GroupLayout JContanInfoLayout = new javax.swing.GroupLayout(JContanInfo);
        JContanInfo.setLayout(JContanInfoLayout);
        JContanInfoLayout.setHorizontalGroup(
            JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JContanInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JContanInfoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                    .addGroup(JContanInfoLayout.createSequentialGroup()
                        .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(txtAddress))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JContanInfoLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnFemale))
                    .addGroup(JContanInfoLayout.createSequentialGroup()
                        .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JContanInfoLayout.createSequentialGroup()
                                .addComponent(rbtnSingle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnMarried)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnWidowed))
                            .addComponent(txtPhone))))
                .addGap(34, 34, 34))
            .addGroup(JContanInfoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JContanInfoLayout.setVerticalGroup(
            JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JContanInfoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel11)
                        .addComponent(rbtnMale)
                        .addComponent(rbtnFemale))
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel12)
                        .addComponent(rbtnSingle)
                        .addComponent(rbtnMarried)
                        .addComponent(rbtnWidowed)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JContanInfoLayout.createSequentialGroup()
                        .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(10, 15, Short.MAX_VALUE))
                    .addGroup(JContanInfoLayout.createSequentialGroup()
                        .addGroup(JContanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtPhone))
                        .addContainerGap())))
        );

        jPanel1.add(JContanInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 720, 140));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Loan Amount:");

        loanAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanAmountMouseEntered(evt);
            }
        });
        loanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmountActionPerformed(evt);
            }
        });
        loanAmount.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                loanAmountPropertyChange(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Annual Income:");

        annualIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annualIncomeActionPerformed(evt);
            }
        });

        loanType.setText("Select type of Loan:");
        loanType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTypeActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Loan Term:");

        loanTerm.setEditable(false);
        loanTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTermActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Select:");

        jLoanHeader.setBackground(new java.awt.Color(0, 0, 102));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Loan Information:");

        loanLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        loanLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jLoanHeaderLayout = new javax.swing.GroupLayout(jLoanHeader);
        jLoanHeader.setLayout(jLoanHeaderLayout);
        jLoanHeaderLayout.setHorizontalGroup(
            jLoanHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoanHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jLoanHeaderLayout.setVerticalGroup(
            jLoanHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoanHeaderLayout.createSequentialGroup()
                .addGroup(jLoanHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(loanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 6, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Down Payment");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Interest Rate:");

        interestRate.setEditable(false);
        interestRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestRateActionPerformed(evt);
            }
        });

        downPayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        downPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JLoanInfoLayout = new javax.swing.GroupLayout(JLoanInfo);
        JLoanInfo.setLayout(JLoanInfoLayout);
        JLoanInfoLayout.setHorizontalGroup(
            JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JLoanInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel28)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(interestRate)
                    .addComponent(loanAmount)
                    .addComponent(loanType, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25))
                .addGap(31, 31, 31)
                .addGroup(JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loanTerm)
                    .addComponent(annualIncome)
                    .addComponent(downPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JLoanInfoLayout.createSequentialGroup()
                .addComponent(jLoanHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JLoanInfoLayout.setVerticalGroup(
            JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JLoanInfoLayout.createSequentialGroup()
                .addComponent(jLoanHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JLoanInfoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(annualIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addGroup(JLoanInfoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JLoanInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loanType)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JLoanInfoLayout.createSequentialGroup()
                        .addGroup(JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JLoanInfoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(loanTerm, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(loanAmount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(downPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JLoanInfoLayout.createSequentialGroup()
                                .addGroup(JLoanInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel28))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(interestRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                    .addComponent(jLabel23))
                .addContainerGap())
        );

        jPanel1.add(JLoanInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        jTitleBar.setBackground(new java.awt.Color(12, 19, 79));
        jTitleBar.setLayout(new java.awt.BorderLayout());

        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        jTitleBar.add(lblTitle, java.awt.BorderLayout.CENTER);

        sidePanel.setBackground(new java.awt.Color(29, 38, 125));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BANKO");

        jButton1.setText("LOAN DASHBOARD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LOAN APPLICATION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 9, 75));
        jLabel26.setText("LOAN APPLICATION");

        btnSubmit.setBackground(new java.awt.Color(0, 0, 102));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit Application");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Loan Information");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Loan Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(jLabel26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(488, 488, 488)
                                .addComponent(btnSubmit)))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel30)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(438, 438, 438)
                    .addComponent(jLabel31)
                    .addContainerGap(439, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 632, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel30)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(315, 315, 315)
                    .addComponent(jLabel31)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JMain main = new JMain(userID);
        main.setVisible(true);
        
        JLoanApplication mainWindow = this;  // Assuming 'this' refers to the current JMain window
        mainWindow.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMaleActionPerformed

    private void rbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemaleActionPerformed

    private void rbtnSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSingleActionPerformed

    private void rbtnMarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMarriedActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        type=loanLabel.getText();
        annualinterest = Double.valueOf(interestRate.getText());
        String loanTermStr = loanTerm.getText();
        String numPart = loanTermStr.replaceAll("[^\\d.]", ""); 
        loanterm = Integer.parseInt(numPart);
         double monthly = calculateLoanDetails();
           try {
        annual = Double.valueOf(annualIncome.getText());
        if(annual<70000){
            JOptionPane.showMessageDialog(null, "Annual Income too low");
            annualIncome.setText("");
        } 
        } catch (NumberFormatException e) {
            // Handle the case when loanAmount is not a valid number
            JOptionPane.showMessageDialog(null, "Invalid Annual amount");
        }
           
            if (loanamount != null && annualinterest != null && loanterm != 0 && annual != null && downpay != null) {
                int loantermM = loanterm * 12;
                LocalDate currentDate = LocalDate.now();
                LocalDate dueDate = currentDate.plusMonths(loantermM);
                LoanApplication lp = new LoanApplication(type,annualinterest,dueDate,loanamount,2);
                this.conn = new Connect();
                conn.loanApply(lp,userID);
                LoanApproval la = new LoanApproval(type,loanamount,annualinterest,loanterm,2);
                conn.loanApproval(la,userID, type);
        } else {
            // Variables are empty
            // Add your code here
        }

           
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void loanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmountActionPerformed
        // TODO add your handling code here:
        try {
        loanamount = Double.parseDouble(loanAmount.getText());
        
    } catch (NumberFormatException e) {
        // Handle the case when loanAmount is not a valid number
        JOptionPane.showMessageDialog(null, "Invalid loan amount");
    }
    }//GEN-LAST:event_loanAmountActionPerformed

    private void annualIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annualIncomeActionPerformed
        // TODO add your handling code here:
        try {
        annual = Double.valueOf(annualIncome.getText());
        if(annual<70000){
            JOptionPane.showMessageDialog(null, "Annual Income too low");
            annualIncome.setText("");
        } 
    } catch (NumberFormatException e) {
        // Handle the case when loanAmount is not a valid number
        JOptionPane.showMessageDialog(null, "Invalid Annual amount");
    }
         
    }//GEN-LAST:event_annualIncomeActionPerformed

    private void loanTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTypeActionPerformed
        try {
        // Create and show the new JTypeAndTerm form
        JTypeAndTerm typeAndTermForm = new JTypeAndTerm();
        typeAndTermForm.setLoanApplicationForm(this); 
        typeAndTermForm.setVisible(true);  
        } catch (NumberFormatException e) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_loanTypeActionPerformed
     public void setTypeLoan(String type) {
        loanLabel.setText(type);
    }

    public void setTermLoan(String term) {
        loanTerm.setText(term);
    }

    public void setInterestRate(Float interest) {
        interestRate.setText(String.valueOf(interest));
    }
    
    public double calculateLoanDetails() {
    double principal = loanamount - downpay;
    double monthlyInterestRate = annualinterest / 12 / 100;
    int loanTermMonths = loanterm * 12;
    double monthlyPayment = (principal * monthlyInterestRate * Math.pow(1 + monthlyInterestRate, loanTermMonths)) /
                            (Math.pow(1 + monthlyInterestRate, loanTermMonths) - 1);

    return monthlyPayment;
    }

    private void loanTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTermActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_loanTermActionPerformed

    private void empFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empFNameActionPerformed

    private void empLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empLNameActionPerformed

    }//GEN-LAST:event_empLNameActionPerformed

    private void empAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empAddressActionPerformed

    private void interestRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestRateActionPerformed

    private void loanAmountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanAmountMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_loanAmountMouseEntered

    private void loanAmountPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_loanAmountPropertyChange
        // TODO add your handling code here:
      
    }//GEN-LAST:event_loanAmountPropertyChange

    private void downPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downPaymentActionPerformed
        // TODO add your handling code here:
        try {
        loanamount = Double.parseDouble(loanAmount.getText());
        if(loanamount>=50000){
            downpay = loanamount * 0.05;
            downPayment.setText(String.format("%.2f", downpay));
        } else {
            downPayment.setText("");  // Clear downPayment field if loanamount is less than or equal to 50000
        }
    } catch (NumberFormatException e) {
        // Handle the case when loanAmount is not a valid number
        JOptionPane.showMessageDialog(null, "Invalid loan amount");
    }
    }//GEN-LAST:event_downPaymentActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int user=1;
                new JLoanApplication(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JContanInfo;
    private javax.swing.JPanel JEmployHeader;
    private javax.swing.JPanel JEmployment;
    private javax.swing.JPanel JLoanInfo;
    private javax.swing.JTextField annualIncome;
    private javax.swing.JTextField appOcupation;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton downPayment;
    private javax.swing.JTextField empAddress;
    private javax.swing.JTextField empFName;
    private javax.swing.JTextField empLName;
    private javax.swing.JTextField empNo;
    private javax.swing.JTextField interestRate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jLoanHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jTitleBar;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField loanAmount;
    private javax.swing.JLabel loanLabel;
    private javax.swing.JTextField loanTerm;
    private javax.swing.JButton loanType;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JRadioButton rbtnMarried;
    private javax.swing.JRadioButton rbtnSingle;
    private javax.swing.JRadioButton rbtnWidowed;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    private void downPayment() {
          try {
            loanamount = Double.parseDouble(loanAmount.getText());
            if(loanamount>50000){
                downpay = loanamount * 0.05;
                downPayment.setText(String.format("%.2f", downpay));
            } else {
                downPayment.setText("");  // Clear downPayment field if loanamount is less than or equal to 50000
            }
        } catch (NumberFormatException e) {
            // Handle the case when loanAmount is not a valid number
            JOptionPane.showMessageDialog(null, "Invalid loan amount");
        }
        }
}
